# Generated by Django 6.0.5 on 2026-05-23 04:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_detallemovimiento_producto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detallemovimiento',
            name='movimiento',
        ),
        migrations.RemoveField(
            model_name='detallemovimiento',
            name='producto',
        ),
        migrations.DeleteModel(
            name='MovimientoInventario',
        ),
        migrations.DeleteModel(
            name='DetalleMovimiento',
        ),
    ]
