# Generated by Django 6.0.5 on 2026-05-23 04:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0019_producto_calificacion'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reseña',
            options={'ordering': ['-creado'], 'verbose_name': 'Reseña', 'verbose_name_plural': 'Reseñas'},
        ),
        migrations.AddField(
            model_name='reseña',
            name='producto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reseñas', to='crud.producto'),
        ),
        migrations.AlterField(
            model_name='reseña',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
