# Generated by Django 6.0.5 on 2026-05-27 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0021_pedido_direccionentrega_detallepedido'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='detallepedido',
            options={'verbose_name': 'Detalle de pedido', 'verbose_name_plural': 'Detalles de pedido'},
        ),
        migrations.AlterModelOptions(
            name='direccionentrega',
            options={'verbose_name': 'Dirección de entrega', 'verbose_name_plural': 'Direcciones de entrega'},
        ),
        migrations.AlterModelOptions(
            name='pedido',
            options={'ordering': ['-creado'], 'verbose_name': 'Pedido', 'verbose_name_plural': 'Pedidos'},
        ),
        migrations.AddField(
            model_name='detallepedido',
            name='cantidad',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='detallepedido',
            name='precio_unitario',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='detallepedido',
            name='subtotal',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='direccionentrega',
            name='calle',
            field=models.CharField(default='calle pendiente', max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='direccionentrega',
            name='departamento',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='direccionentrega',
            name='numero',
            field=models.CharField(default=0, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='direccionentrega',
            name='referencia',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pedido',
            name='cliente_email',
            field=models.EmailField(default='sin@email.com', max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pedido',
            name='cliente_nombre',
            field=models.CharField(default='Cliente pendiente', max_length=120),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pedido',
            name='cliente_telefono',
            field=models.CharField(default='000000000', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pedido',
            name='estado',
            field=models.CharField(choices=[('PENDIENTE_PAGO', 'Pendiente de pago'), ('PAGADO', 'Pagado'), ('PREPARANDO', 'Preparando pedido'), ('LISTO_RETIRO', 'Listo para retiro'), ('ENVIADO', 'Enviado'), ('ENTREGADO', 'Entregado'), ('CANCELADO', 'Cancelado')], default='PENDIENTE_PAGO', max_length=30),
        ),
        migrations.AddField(
            model_name='pedido',
            name='metodo_entrega',
            field=models.CharField(choices=[('RETIRO', 'Retiro'), ('DOMICILIO', 'Envío a domicilio')], default='DOMICILIO', max_length=20),
        ),
    ]
