# Generated by Django 6.0.5 on 2026-05-27 20:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0024_perfilusuario_favorito'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='calificacion',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=2),
        ),
        migrations.CreateModel(
            name='ModeloAuto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
                ('marca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modelos', to='crud.marca')),
            ],
            options={
                'ordering': ['nombre'],
                'unique_together': {('marca', 'nombre')},
            },
        ),
        migrations.AddField(
            model_name='producto',
            name='modelo_auto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='productos', to='crud.modeloauto'),
        ),
    ]
