# Generated by Django 6.0.5 on 2026-05-28 05:44

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0025_alter_producto_calificacion_modeloauto_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='direccionentrega',
            options={},
        ),
        migrations.RenameField(
            model_name='direccionentrega',
            old_name='numero',
            new_name='telefono',
        ),
        migrations.RemoveField(
            model_name='direccionentrega',
            name='calle',
        ),
        migrations.RemoveField(
            model_name='direccionentrega',
            name='departamento',
        ),
        migrations.RemoveField(
            model_name='direccionentrega',
            name='pedido',
        ),
        migrations.RemoveField(
            model_name='direccionentrega',
            name='referencia',
        ),
        migrations.AddField(
            model_name='direccionentrega',
            name='actualizado',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='direccionentrega',
            name='creado',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='direccionentrega',
            name='detalle',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='direccionentrega',
            name='direccion',
            field=models.CharField(default=django.utils.timezone.now, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='direccionentrega',
            name='nombre_completo',
            field=models.CharField(default='', max_length=120),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='direccionentrega',
            name='usuario',
            field=models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, related_name='direccion_entrega', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
