# Generated by Django 6.0.5 on 2026-05-30 05:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0026_alter_direccionentrega_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='codigo_seguimiento',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='pedido',
            name='nota_despacho',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pedido',
            name='transporte',
            field=models.CharField(blank=True, choices=[('RETIRO_LOCAL', 'Retiro en local'), ('ZEEZTON_EXPRESS', 'Despacho Zeezton'), ('CHILEXPRESS', 'Chilexpress'), ('STARKEN', 'Starken'), ('BLUEXPRESS', 'Blue Express'), ('OTRO', 'Otro')], max_length=30, null=True),
        ),
        migrations.CreateModel(
            name='DireccionUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('telefono', models.CharField(max_length=20)),
                ('region', models.CharField(max_length=100)),
                ('comuna', models.CharField(max_length=100)),
                ('calle', models.CharField(max_length=150)),
                ('numero', models.CharField(max_length=20)),
                ('referencia', models.TextField(blank=True, null=True)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
