# Generated by Django 6.0.5 on 2026-06-01 23:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0027_pedido_codigo_seguimiento_pedido_nota_despacho_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TarifaEnvio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comuna', models.CharField(max_length=100, unique=True)),
                ('costo', models.PositiveIntegerField(default=0)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Tarifa de envío',
                'verbose_name_plural': 'Tarifas de envío',
                'ordering': ['comuna'],
            },
        ),
        migrations.RemoveField(
            model_name='direccionentrega',
            name='detalle',
        ),
        migrations.RemoveField(
            model_name='direccionentrega',
            name='direccion',
        ),
        migrations.AddField(
            model_name='direccionentrega',
            name='calle',
            field=models.CharField(default='', max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='direccionentrega',
            name='numero',
            field=models.CharField(default='', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='direccionentrega',
            name='predeterminada',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='direccionentrega',
            name='referencia',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='direccionentrega',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='direcciones_entrega', to=settings.AUTH_USER_MODEL),
        ),
    ]
