# Generated by Django 5.2.14 on 2026-06-02 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0028_tarifaenvio_remove_direccionentrega_detalle_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='estado_pago',
            field=models.CharField(default='pendiente', max_length=30),
        ),
        migrations.AddField(
            model_name='pedido',
            name='mercadopago_id',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
