# Generated by Django 5.2.14 on 2026-06-05 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0029_pedido_estado_pago_pedido_mercadopago_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='suscriptor',
            options={'ordering': ['-creado'], 'verbose_name': 'Suscriptor', 'verbose_name_plural': 'Suscriptores'},
        ),
        migrations.AddField(
            model_name='pedido',
            name='stock_descontado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='suscriptor',
            name='activo',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='suscriptor',
            name='actualizado',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='tarifaenvio',
            name='actualizado',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='tarifaenvio',
            name='creado',
            field=models.DateTimeField(auto_now_add=True, default='2026-01-01 00:00:00'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='suscriptor',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
