# Generated by Django 5.2.3 on 2026-08-01 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0030_alter_suscriptor_options_pedido_stock_descontado_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MensajeContacto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_mensaje', models.CharField(choices=[('IMPORTACION', 'Importación o búsqueda de repuesto'), ('COMPATIBILIDAD', 'Consulta de compatibilidad'), ('PEDIDO', 'Consulta sobre una compra o pedido'), ('CALIFICACION', 'Calificación o reseña'), ('SUGERENCIA', 'Sugerencia para mejorar'), ('OTRO', 'Otra consulta')], default='IMPORTACION', max_length=20, verbose_name='Tipo de mensaje')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
                ('email', models.EmailField(max_length=254, verbose_name='Correo electrónico')),
                ('telefono', models.CharField(blank=True, max_length=30, verbose_name='Teléfono')),
                ('vehiculo', models.CharField(blank=True, help_text='Ejemplo: BMW 320i 2018', max_length=160, verbose_name='Vehículo')),
                ('repuesto', models.CharField(blank=True, max_length=200, verbose_name='Repuesto solicitado')),
                ('numero_pedido', models.CharField(blank=True, max_length=80, verbose_name='Número de pedido')),
                ('calificacion', models.IntegerField(blank=True, choices=[(1, '1 ★'), (2, '2 ★'), (3, '3 ★'), (4, '4 ★'), (5, '5 ★')], null=True, verbose_name='Calificación')),
                ('comentario', models.TextField(verbose_name='Mensaje')),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('atendido', models.BooleanField(default=False, verbose_name='Mensaje atendido')),
            ],
            options={
                'verbose_name': 'Mensaje de contacto',
                'verbose_name_plural': 'Mensajes de contacto',
                'ordering': ['-creado'],
            },
        ),
    ]
